<a href="https://colab.research.google.com/github/nnh92/Ex92-100/blob/main/Ex93.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def Inp_Matrix(n1, n2):
  A = np.zeros((n1,n2))
  for i in range(n1):
    for j in range(n2):
      print('Nhap hang {}, cot {}: '.format(i+1,j+1))
      A[i][j] = int(input(''))

  return A

def Trans_Matrix(A):
  AT = np.zeros((A.shape[1],A.shape[0]))
  for i in range(A.shape[1]):
    for j in range(A.shape[0]):
      AT[i][j] = A[j][i]

  return AT

n1 = int(input('Nhap so hang: '))
n2 = int(input('Nhap so cot: '))

A = Inp_Matrix(n1, n2)

print('Matrix input:')
print(A)
print('Matrix output: ')
print(Trans_Matrix(A))


Nhap so hang: 2
Nhap so cot: 3
Nhap hang 1, cot 1: 
1
Nhap hang 1, cot 2: 
2
Nhap hang 1, cot 3: 
3
Nhap hang 2, cot 1: 
4
Nhap hang 2, cot 2: 
5
Nhap hang 2, cot 3: 
6
Matrix input:
[[1. 2. 3.]
 [4. 5. 6.]]
Matrix output: 
[[1. 4.]
 [2. 5.]
 [3. 6.]]
