<a href="https://colab.research.google.com/github/nnh92/Ex92-100/blob/main/Ex94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def Inp_Matrix(n1, n2):
  A = np.zeros((n1,n2))
  for i in range(n1):
    print('Nhap phan tu hang {}: '.format(i+1))
    lst = list(map(float, input('').split()))
    if len(lst) != n2:
      print('Nhap lai day so')
    else:
      for j in range(n2):
        A[i][j] = lst[j]
  return A

def Count_Matrix(A):
  values, count = np.unique(A, return_counts = True)
  Alst = values.tolist()
  Acount = count.tolist()
  lst = []
  for i in range(len(Alst)):
    if int(Acount[i]) >= A.shape[0]:
      lst.append(values[i])
  return lst

def List_Matrix(lst, A):
  lst = 
  return lst

n1 = int(input('Nhap so hang: '))
n2 = int(input('Nhap so cot: '))

A = Inp_Matrix(n1, n2)

print('Matrix input:')
print(A)

lst = Count_Matrix(A)

print('Matrix output: ')
print(List_Matrix(lst, A))


Nhap so hang: 3
Nhap so cot: 4
Nhap phan tu hang 1: 
1 2 3 4
Nhap phan tu hang 2: 
1 3 1 4
Nhap phan tu hang 3: 
1 1 3 7
Matrix input:
[[1. 2. 3. 4.]
 [1. 3. 1. 4.]
 [1. 1. 3. 7.]]
Matrix output: 
[1.0, 3.0]
