<a href="https://colab.research.google.com/github/nnh92/Ex92-100/blob/main/Ex94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

def Inp_Matrix(n1, n2):
  A = np.zeros((n1,n2))
  for i in range(n1):
    print('Nhap phan tu hang {}: '.format(i+1))
    lst = list(map(float, input('').split()))
    if len(lst) != n2:
      print('Nhap lai day so')
    else:
      for j in range(n2):
        A[i][j] = lst[j]

  return A

def Count_Matrix(A):
  values, count = np.unique(A, return_counts = True)
  Alst = A.tolist()
  lst = [i for i in range(len(Alst)) if Alst.count(i) >= A.shape[1]]
#  for i in range(A.shape[0]):
#    for j in range(A.shape[1]):
#      lst = [A[i][j] if np.count_nonzeroe(A.)  A.shape[1]]

  return values, count

n1 = int(input('Nhap so hang: '))
n2 = int(input('Nhap so cot: '))

A = Inp_Matrix(n1, n2)

print('Matrix input:')
print(A)
print('Matrix output: ')
print(Count_Matrix(A))


Nhap so hang: 2
Nhap so cot: 3
Nhap phan tu hang 1: 
1 2 3
Nhap phan tu hang 2: 
1 3 4
Matrix input:
[[1. 2. 3.]
 [1. 3. 4.]]
Matrix output: 
(array([1., 2., 3., 4.]), array([2, 1, 2, 1]))
